In [2]:
import torch
t1=torch.tensor([4,2])
t2=torch.tensor([3,2])
t1*t2

tensor([12,  4])

In [3]:
t1=torch.zeros([3,2])
t1

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [4]:
t1.shape

torch.Size([3, 2])

In [7]:
t1=torch.rand([3,2])
t1

tensor([[0.9531, 0.8053],
        [0.9276, 0.2072],
        [0.9265, 0.5170]])

In [8]:
t1.view([1,6])

tensor([[0.9531, 0.8053, 0.9276, 0.2072, 0.9265, 0.5170]])

In [10]:
t1=t1.view([1,6])
t1

tensor([[0.9531, 0.8053, 0.9276, 0.2072, 0.9265, 0.5170]])