In [1]:
import cv2
import numpy as np

In [4]:
img = cv2.imread("image1.jfif", 1)

# im = cv2.cvtColor(im, cv2.COLOR_RGB2GRAY) --------------------------> default 

In [15]:
"""
imshow() is used to show the read image and takes two parameters: 1. window-name and 2. image to be returned
"""
cv2.imshow('Image',img)

"""
cv2.waitKey() specifies the total time duration of the display.
If passed 0, it will showcase the output till any key is hit. It takes parameters as time in milliseconds.
The function is very important as it avoids the Python kernel from crashing.
"""
cv2.waitKey(0)

"""
closes all the open windows.
"""

cv2.destroyAllWindows()

#### For GrayScale

In [12]:
img = cv2.imread("image1.jfif", 0)

In [13]:
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### Picture Scaling

In [22]:
# img = cv2.resize(img, (700,500))

In [23]:
# cv2.imshow('Image',img)
# # cv2.waitKey(0)
# cv2.destroyAllWindows()

In [3]:
img = cv2.resize(img, (0,0), fx=0.3, fy=0.3)

NameError: name 'img' is not defined

In [25]:
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [30]:
"""
the third argument is related to grayscale since I gave colored image thats why it should(150,10,3)
"""
print(img)
print(img.shape) #returns shape of numpy array


[[[242 220 184]
  [243 221 184]
  [242 223 183]
  ...
  [237 216 179]
  [237 215 178]
  [237 215 177]]

 [[243 221 185]
  [243 223 185]
  [242 223 185]
  ...
  [238 217 179]
  [238 217 179]
  [238 217 179]]

 [[242 222 187]
  [242 223 185]
  [242 223 185]
  ...
  [237 218 179]
  [237 217 179]
  [238 217 179]]

 ...

 [[154 122  99]
  [153 123  97]
  [153 124  97]
  ...
  [143 112  89]
  [143 112  88]
  [142 111  88]]

 [[154 122  99]
  [153 123  97]
  [152 123  97]
  ...
  [142 111  88]
  [142 111  89]
  [141 110  88]]

 [[153 120  99]
  [152 121  96]
  [151 121  96]
  ...
  [141 109  88]
  [141 110  87]
  [141 110  88]]]
(150, 210, 3)


# Detect Eyes and Detect Faces

In [48]:
import cv2
import sys

In [49]:
imagePath = sys.argv[1]


In [50]:
imagePath = 'image1.jfif'
cascPath = "haarcascade_frontalface_default.xml"

In [51]:
# Create the haar cascade
faceCascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades +  "haarcascade_eye.xml")

In [52]:
# Read the image
image = cv2.imread(imagePath)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

In [53]:
# faceCascade = cv2.CascadeClassifier(cascPath)

In [54]:
# Read the image
image = cv2.imread(imagePath)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

In [55]:
# Detect faces in the image
faces = faceCascade.detectMultiScale(
    gray,
    scaleFactor=1.1,
    minNeighbors=5,
    minSize=(30, 30),
    flags = cv2.CASCADE_SCALE_IMAGE
)

In [56]:
print ("Found {0} faces!".format(len(faces)))

# Draw a rectangle around the faces
for (x, y, w, h) in faces:
    cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)

Found 1 faces!


In [57]:
cv2.imshow("Faces found", image)
cv2.waitKey(0)

-1